---
# deploy_rancher_on_k3s/tasks/main.yml

#
# namespace for cert-manager
#

- name: 'Create the namespace for cert-manager'
  template:
    src: 'cert-manager_namespace.yml.j2'
    dest: "{{ k3s_manifest_directory }}/cert-manager_namespace.yml"
    owner: 'root'
    group: 'root'
    mode: '0644'

#
# namespace for Rancher
#

- name: 'Create the namespace for Rancher'
  template:
    src: 'rancher_namespace.yml.j2'
    dest: "{{ k3s_manifest_directory }}/rancher_namespace.yml"
    owner: 'root'
    group: 'root'
    mode: '0644'

#
# Install cert-manager
#

- name: 'Download the cert-manager CRD manifest'
  ansible.builtin.get_url:
    url: "https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml"
    dest: "{{ k3s_manifest_directory }}/cert-manager.crds.yaml"
    mode: '0644'

- name: 'Install cert-manager'
  template:
    src: 'cert-manager_helm_chart.yml.j2'
    dest: "{{ k3s_manifest_directory }}/cert-manager_helm_chart.yml"
    owner: 'root'
    group: 'root'
    mode: '0644'

#
# Install Rancher
#

- name: 'Install Rancher'
  template:
    src: 'rancher_helm_chart.yml.j2'
    dest: "{{ k3s_manifest_directory }}/rancher_helm_chart.yml"
    owner: 'root'
    group: 'root'
    mode: '0644'
